FROM alpine
RUN apk add nghttp2-static nghttp2-dev openssl-libs-static openssl-dev libcrypto1.1 cmake boost-static boost-dev luajit-dev gcc g++ unzip wget libexecinfo-dev libexecinfo-static make && \
    wget https://github.com/Tencent/rapidjson/archive/refs/heads/master.zip && \
    unzip master.zip && \
    cd rapidjson-master && cmake . && cmake --build ./ && cmake --install ./ && \
    cd .. && \
    rm rapidjson-master master.zip -rf && \
    wget https://github.com/microsoft/mimalloc/archive/refs/heads/master.zip && \
    unzip master.zip && \
    cmake -S mimalloc-master -B mimalloc-master/build -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build mimalloc-master/build && \
    cp $(find ./ -name libmimalloc.a) /lib/ && \
    rm -rf mimalloc-master master.zip && \
    wget https://github.com/wallyatgithub/maock/archive/refs/heads/main.zip && \
    unzip main.zip && \
    cmake -S maock-main -B maock-main/build -DCMAKE_BUILD_TYPE=Release .. -DALPINE_STATIC=ON && \
    cmake --build maock-main/build && \
    cp maock-main/build/maock /usr/bin/ && \
    mkdir -p /usr/share/maock/ && \
    cp maock-main/H2Server_Config_Schema.json /usr/share/maock/ && \
    rm -rf maock-main main.zip && \
    apk del nghttp2-static nghttp2-dev openssl-libs-static openssl-dev libcrypto1.1 cmake boost-static boost-dev luajit-dev gcc g++ unzip wget libexecinfo-dev libexecinfo-static make
